accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('update/', views.update, name="update"),
    path('delete/', views.delete, name="delete"),
    path('password/', views.password, name="password"),
    
    path('<int:user_id>/follow/', views.follow, name="follow"),
    
    path('<int:user_id>/vuefollow/', views.vue_follow),
    path('<int:user_id>/checkfollow/', views.check_follow),
]

instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views as accounts_views
from posts import views as posts_views

urlpatterns = [
    path('', posts_views.list, name="root"),
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('<str:username>/', accounts_views.people, name="people"),
]

# urlpatterns += static(통과시키고자 하는 url, 실제 저장 장소)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path('create/', views.create, name="create"),
    path('', views.list, name="list"),
    path('<int:post_id>/delete/', views.delete, name="delete"),
    path('<int:post_id>/update/', views.update, name="update"),
    path('<int:post_id>/like/', views.like, name="like"),
    
    path('<int:post_id>/comment/create/', views.comment_create, name="comment_create"),
    path('<int:post_id>/comment/<int:comment_id>/delete/', views.comment_delete, name="comment_delete"),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser


# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    nickname = models.CharField(max_length=40, blank=True)
    image = models.ImageField(blank=True)
    
    
    
class User(AbstractUser):
    follows = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followers")

posts/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.conf import settings

# Create your models here.


class Post(models.Model):
    content = models.CharField(max_length=150)
    image = models.ImageField(blank=True)
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts", blank=True)
    
    def __str__(self):
        return f"{self.id}: {self.content}"
        
        
class Comment(models.Model):
    content = models.CharField(max_length=200)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.content

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model
from django import forms
from .models import Profile


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name',)
        
        
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('description', 'nickname', 'image',)
        
        
class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(
        label="",
        widget=forms.TextInput(attrs={
            "placeholder": "사용자 이름",
        })
    )
    password1 = forms.CharField(
        label="",
        widget=forms.PasswordInput(attrs={
            "placeholder": "비밀번호",
        }),
    )
    password2 = forms.CharField(
        label="",
        widget=forms.PasswordInput(attrs={
            "placeholder": "비밀번호 확인",
        }),
    )
    
    class Meta(UserCreationForm.Meta):
        model = get_user_model()

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import get_user_model, update_session_auth_hash
from .forms import CustomUserChangeForm, ProfileForm, CustomUserCreationForm
from .models import Profile

from django.http import JsonResponse

# Create your views here.


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            # next= 정의되어 있으면 
            return redirect(request.GET.get('next') or 'posts:list')
        return redirect('accounts:login')
    else:
        form = AuthenticationForm()
        return render(request, 'accounts/login.html', {'form': form})
        


def logout(request):
    auth_logout(request)
    return redirect('posts:list')
    
    
def signup(request):
    # POST: 유저 등록
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user)
            auth_login(request, user)
            return redirect('posts:list')
        return redirect('accounts:signup')
    # GET: 유저 정보 입력
    else:
        form = CustomUserCreationForm()
        return render(request, 'accounts/signup.html', {'form': form})
        
        
def people(request, username):
    # 사용자에 대한 정보
    person = get_object_or_404(get_user_model(), username=username)
    # 1. settings.AUTH_USER_MODEL(django.conf)
    # 2. get_user_model()(django.contrib.auth) - 쓸 것
    # 3. User(django.contrib.auth.models) - 쓰지 말 것
    return render(request, 'accounts/people.html', {'person': person})
    
    
# 회원 정보 변경(편집, 반영)
def update(request):
    if request.method == "POST":
        user_change_form = CustomUserChangeForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if user_change_form.is_valid() and profile_form.is_valid():
            user = user_change_form.save()
            profile_form.save()
            return redirect('people', user.username)
    else:
        user_change_form = CustomUserChangeForm(instance=request.user)
        # 1. instance 넣어줄 정보가 있는 User가 있고 없는 User도 있다.
        profile, created = Profile.objects.get_or_create(user=request.user)
        profile_form = ProfileForm(instance=profile)
        context = {
            'user_change_form': user_change_form,
            'profile_form': profile_form,
        }
        return render(request, 'accounts/update.html', context)
        
        
def delete(request):
    if request.method == "POST":
        request.user.delete()
        return redirect('posts:list')
    return render(request, 'accounts/delete.html')
    
    
def password(request):
    if request.method == "POST":
        password_change_form = PasswordChangeForm(request.user, request.POST)
        if password_change_form.is_valid():
            user = password_change_form.save()
            update_session_auth_hash(request, user)
            return redirect('people', user.username)
    else:
        password_change_form = PasswordChangeForm(request.user)
        context = {
            'password_change_form': password_change_form,
        }
        return render(request, 'accounts/password.html', context)
        
        
def follow(request, user_id):
    person = get_object_or_404(get_user_model(), id=user_id)
    
    if request.user != person:
    # 현재 유저가 해당 유저를 팔로우하고 있었으면
        if request.user in person.followers.all():
        # 언팔로우
            person.followers.remove(request.user)
        # 아니면
        else:
        # 팔로우
            person.followers.add(request.user)
    return redirect('people', person.username)
    
    
def vue_follow(request, user_id):
    person = get_object_or_404(get_user_model(), id=user_id)
    
    if request.user != person:
    # 현재 유저가 해당 유저를 팔로우하고 있었으면
        if request.user in person.followers.all():
        # 언팔로우
            person.followers.remove(request.user)
            followed = False
        # 아니면
        else:
        # 팔로우
            person.followers.add(request.user)
            followed = True
    return JsonResponse({'followed': followed})
    
    
def check_follow(request, user_id):
    person = get_object_or_404(get_user_model(), id=user_id)
    
    if request.user != person:
        # 현재 유저가 해당 유저를 팔로우하고 있었으면
        if request.user in person.followers.all():
            followed = True
        # 아니면
        else:
            followed = False
    return JsonResponse({'followed': followed})

accounts/templates/accounts/delete.html
{% extends 'base.html' %}

{% block body %}
  <form method="POST">
    {% csrf_token %}
    <p>정말로 탈퇴하시겠습니까 ㅠㅠ</p>
    <button class="btn btn-danger" type="submit">미안하다</button>
  </form>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
  <h1 class="text-center">로그인</h1>
  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary">로그인</button>
  </form>
{% endblock %}

accounts/templates/accounts/password.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
  <h1 class="text-center">비밀번호 변경</h1>
  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form password_change_form %}
    <button type="submit" class="btn btn-primary">수정</button>
  </form>
{% endblock %}

accounts/templates/accounts/people.html
{% extends 'base.html' %}

{% block body %}
  <div class="container my-5">
    <div class="row profile">
      <div class="col-4 d-flex">
        <div class="col-12 d-flex justify-content-center align-items-center">
          <img src={% if person.profile.image %}"{{ person.profile.image.url }}"{% else %}"https://i.stack.imgur.com/34AD2.jpg"{% endif %} width="150rem" style="border-radius: 50%; image-size: contain;" alt="">
        </div>
      </div>
      <div class="col-8">
        <h2>{{ person.username }}
          {% if user != person %}
            <!-- 만약 현재 접속한 유저가 해당 페이지의 유저를 팔로우 한 경우 -->
            {% if user in person.followers.all %}
              <a class="btn btn-outline-primary ml-3" href="{% url 'accounts:follow' person.id %}">
                언팔로우
              </a>
            {% else %}
              <a class="btn btn-primary ml-3" href="{% url 'accounts:follow' person.id %}">
                팔로우
              </a>
            {% endif %}
          {% else %}
            <a class="btn btn-outline-info ml-3" href="{% url 'accounts:update' %}">프로필 편집</a>
            <button type="button" class="btn" data-toggle="modal" data-target="#ProfileModal"><i class="far fa-sun"></i></button>
            <div class="modal fade" id="ProfileModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-body">
                    <a class="profile-modal-btn" href="{% url 'accounts:password' %}"><button class="btn">비밀번호 변경</button></a>
                    <a class="profile-modal-btn" href="{% url 'accounts:logout' %}"><button class="btn">로그아웃</button></a>
                    <a class="profile-modal-btn" href="{% url 'accounts:delete' %}"><button class="btn">회원 탈퇴</button></a>
                    <a class="profile-modal-btn"><button class="btn" data-dismiss="modal">취소</button></a>
                  </div>
                </div>
              </div>
            </div>
          {% endif %}
        </h2>
        
        <div id="app">
          <!-- Vuejs로 작동하는 팔로우 버튼 -->
          <button v-show="loading" @click="follow({{ person.id }})" :class="{'btn': true, 'btn-primary': !followed, 'btn-dark': followed}">Vue 팔로우</button>
          <p>[[ test ]]</p>
          <p>팔로우 여부 : [[ followed ]]</p>
        </div>
        
        <ul class="list-group list-group-horizontal mt-3">
          <li class="simple-description">
            <span>게시물 <strong>{{ person.post_set.count }}</strong></span>
          </li>
          <li class="simple-description">
            <span>팔로워 <strong>{{ person.followers.count }}</strong></span>
          </li>
          <li class="simple-description">
            <span>팔로우 <strong>{{ person.follows.count }}</strong></span>
          </li>
        </ul>
        <div class="mt-3">
          <span><strong class="mr-3">{{ person.last_name }} {{ person.first_name }}</strong>{{ person.profile.nickname }}</span><br>
          <span>{{ person.profile.description }}</span>
        </div>
      </div>
    </div>
    
    <div class="row">
      {% for post in person.post_set.all %}
        <div class="col-4">
          <img src="{{ post.image.url }}" class="img-fluid">
        </div>
      {% endfor %}
    </div>
  </div>

<script>
  const app = new Vue({
    delimiters: ['[[', ']]'],
    el: '#app',
    data: {
      test: '뷰 잘 동작하니?',
      followed: false,
      loading: false
    },
    methods: {
      follow: function(personId) {
        axios.get(`/accounts/${personId}/vuefollow/`)
          .then(res => {
            console.log(res.data.followed)
            this.followed = res.data.followed
          })
      },
      checkFollow: function(personId) {
        axios.get(`/accounts/${personId}/checkfollow/`)
          .then(res => {
            console.log(res.data.followed)
            this.followed = res.data.followed
            this.loading = true
          })
      }
    },
    beforeMount: function() {
      this.checkFollow({{ person.id }})
    }
  })
</script>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
  <div class="row my-5">
    <div class="col-4 offset-2">
      .
    </div>
    <div class="col-4 signup">
      <div class="signup-box">
        <h1 class="text-center mb-4" id="title">Instagram</h1>
        <form method="POST">
          <div>
            <h5 class="text-center" id="signup-comment">친구들의 사진과 동영상을 보려면 가입하세요.</h5>
          </div>
          {% csrf_token %}
          {% bootstrap_form form %}
          <button type="submit" class="btn btn-primary col-12 mb-3">회원가입</button>
        </form>
        <p class="agreement">
          가입하면 Instagram의 <strong>약관</strong>, <strong>데이터 정책</strong> 및 <strong>쿠키 정책</strong>에 동의하게 됩니다.
        </p>
      </div>
      <div class="login-box">
        <p class="mb-0">계정이 있으신가요? <a href="{% url 'accounts:login' %}" class="text-decoration-none">로그인</a></p>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
  <div class="row">
    <div class="col-2 offset-2">
      .
    </div>
    <div class="col-6 profile-edit-box">
      <h1 class="text-center">회원 정보 변경</h1>
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form user_change_form %}
        {% bootstrap_form profile_form %}
        <button type="submit" class="btn btn-primary">수정</button>
      </form>
    </div>
  </div>
{% endblock %}