instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views as accounts_views
from posts import views as posts_views

urlpatterns = [
    path('', posts_views.list, name="root"),
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('<str:username>/', accounts_views.people, name="people"),
]

# urlpatterns += static(통과시키고자 하는 url, 실제 저장 장소)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path('create/', views.create, name="create"),
    path('', views.list, name="list"),
    path('<int:post_id>/delete/', views.delete, name="delete"),
    path('<int:post_id>/update/', views.update, name="update"),
    path('<int:post_id>/like/', views.like, name="like"),
    
    path('<int:post_id>/comment/create/', views.comment_create, name="comment_create"),
    path('<int:post_id>/comment/<int:comment_id>/delete/', views.comment_delete, name="comment_delete"),
]

posts/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.conf import settings

# Create your models here.


class Post(models.Model):
    content = models.CharField(max_length=150)
    image = models.ImageField(blank=True)
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts", blank=True)
    
    def __str__(self):
        return f"{self.id}: {self.content}"
        
        
class Comment(models.Model):
    content = models.CharField(max_length=200)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.content

posts/forms.py
from django import forms
from .models import Post, Comment

# Post라는 모델을 조작할 수 있는 PostModelForm 정의
class PostModelForm(forms.ModelForm):
    # 1. 어떤 input 필드를 가지는지
    content = forms.CharField(label="내용", widget=forms.Textarea(attrs={
        'placeholder': '오늘은 무엇을 하셨나요?',
    }))
    # 2. 해당 input 필드의 속성을 추가 & 어떤 모델을 조작할지
    class Meta:
        model = Post
        fields = ['content', 'image']
        
        
class CommentForm(forms.ModelForm):
    content = forms.CharField(label="댓글")
    
    class Meta:
        model = Comment
        fields = ('content',)

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostModelForm, CommentForm
from .models import Post, Comment
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.db.models.query_utils import Q
from django.contrib.auth import get_user_model

# Create your views here.


def create(request):
    if request.method == 'POST':
        # 작성된 post를 DB에 적용
        form = PostModelForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:list')
        return redirect('posts:create')
    else:
        # post를 작성하는 form을 보여줌
        form = PostModelForm()
        return render(request, 'posts/create.html', {'form': form})
        
        
@login_required
def list(request):
    # 1. 내가 팔로우한 사람들의 Post를 보여줌
    posts = Post.objects.filter(Q(user_id__in=request.user.follows.all()) | Q(user=request.user))
    form = CommentForm()
    return render(request, 'posts/list.html', {'posts': posts, 'form': form})
    
    
def delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    
    if post.user != request.user:
        return redirect('posts:list')
        
    post.delete()
    return redirect('posts:list')


def update(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    
    if post.user != request.user:
        return redirect('posts:list')
        
    if request.method == 'POST':
        form = PostModelForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts:list')
        return redirect('posts:update')
    else:
        form = PostModelForm(instance=post)
        return render(request, 'posts/create.html', {'form': form})
        
        
@login_required
def like(request, post_id):
    # 1. like를 추가할 포스트를 가져옴
    post = get_object_or_404(Post, id=post_id)
    # 2. 만약 유저가 해당 post를 이미 like 했다면
    #   like를 제거하고
    # 아니면
    #   like를 추가한다.
    if request.user in post.like_users.all():
        post.like_users.remove(request.user)
    else:
        post.like_users.add(request.user)
    return redirect('posts:list')
    

@login_required
@require_POST
def comment_create(request, post_id):
    form = CommentForm(request.POST)
    post = get_object_or_404(Post, id=post_id)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.user = request.user
        comment.save()
    return redirect('posts:list')
    
    
def comment_delete(request, post_id, comment_id):
    comment = Comment.objects.get(id=comment_id)
    if request.user == comment.user:
        comment.delete()
    return redirect('posts:list')
        

posts/templates/posts/create.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <!-- 모델 폼 -->
  {% bootstrap_form form %}
  {% if 'create' in request.path %}
    <button type="submit" class="btn btn-primary">업로드</button>
  {% else %}
    <button type="submit" class="btn btn-primary">수정</button>
  {% endif %}
</form>
{% endblock %}

posts/templates/posts/list.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
  <!--<div class="row justify-content-center">-->
  <div class="card-columns">
    {% for post in posts %}
      <div class="card mb-2" style="width: 20rem;">
        <div class="card-header">
          <span><a href="{% url 'people' post.user.username %}">{{ post.user }}</a></span>
        </div>
        
        <img src="{{ post.image.url }}" class="card-img-top" alt="...">
        <div class="card-body">
          <p class="card-text">{{ post.content }}</p>
          
          <!-- 작성자만 수정/삭제 가능 -->
          {% if post.user == request.user %}
            <a href="{% url 'posts:delete' post.id %}" class="btn btn-danger">삭제</a>
            <a href="{% url 'posts:update' post.id %}" class="btn btn-success">수정</a>
          {% endif %}
        </div>
        <!-- 좋아요 버튼 -->
        <div class="card-body">
          <a href="{% url 'posts:like' post.id %}">
            <!-- 해당 유저가 like를 했으면 -->
            {% if user in post.like_users.all %}
              <i class="fas fa-heart"></i>
            <!-- 아니면 -->
            {% else %}
              <i class="far fa-heart"></i>
            {% endif %}
          </a>
          <p class="card-text">
            {{ post.like_users.count }}명이 좋아합니다.
          </p>
        </div>
        
        <div class="card-body">
          <!-- Comment에 대한 ModelForm -->
          <form action="{% url 'posts:comment_create' post.id %}" method="POST">
            <!-- bootstrap_form -->
            {% csrf_token %}
            <div class="row">
              <div class="col-9 pr-1">
                {% bootstrap_form form %}
              </div>
              <div class="col-3 pl-1 d-flex align-items-center">
                <button type="submit" class="btn btn-info">등록</button>
              </div>
            </div>
          </form>
          <!-- 해당 글에 작성된 댓글을 모두 출력 -->
          <div class="card-body">
            {% for comment in post.comment_set.all %}
              <div class="row">
                <div class="col-10">
                  <strong>{{ comment.user }}</strong>
                  {{ comment.content }}
                </div>
                {% if request.user == comment.user %}
                  <a href="{% url 'posts:comment_delete' post.id comment.id %}">[삭제]</a>
                {% endif %}
              </div>
              <hr>
            {% endfor %}
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}